### ISSUE TITLE
addSidebarContentPanel: Failed to find element with selector

### ISSUE THREAD

**Issue by Dottenpixel** [InboxSDK/thread-sidebar#1]
This is the error I get when first loading a threadview, implementing the example code on this repo. subsequent visits to a thread view produce the same error, but the selector it is looking for is different with each thread

my implementation:
```
sdk.Conversations.registerThreadViewHandler(threadView => {
      console.log("InboxSDK.registerThreadthreadViewHandler");
      const el = document.createElement("div");
      el.innerHTML = 'Hello world!';

      threadView.addSidebarContentPanel({
        iconUrl: chrome.runtime.getURL('images/icon_48.png'),
        title: "This was created by InboxSDK",
        el
      })
    })
```

```
platform-implementation.js:80 Error logged: Error: Failed to find element with selector: .J-KU-Jz
    at r (platform-implementation.js:104)
    at e.value (platform-implementation.js:92)
    at new e (platform-implementation.js:92)
    at e.value (platform-implementation.js:93)
    at t.value (platform-implementation.js:110)
    at content-classes.js? [sm]:1006
    at i (platform-implementation.js:105)
    at e.value (platform-implementation.js:105)
    at e.value (platform-implementation.js:105)
    at eval (platform-implementation.js:108)
    at m (platform-implementation.js:42)
    at _.dispatch (platform-implementation.js:42)
    at Ue._emitValue (platform-implementation.js:42)
    at Ue._handleSubAny (platform-implementation.js:43)
    at Oe._$handleSubAny (platform-implementation.js:42)
    at m (platform-implementation.js:42)
    at Object._on (platform-implementation.js:42)
    at Object.onAny (platform-implementation.js:42)
    at Ue._addToCur (platform-implementation.js:43)
    at Ue._add (platform-implementation.js:43)
    at Ue._handleMain (platform-implementation.js:43)
    at Ue._$handleMain (platform-implementation.js:42)
    at m (platform-implementation.js:42)
    at _.dispatch (platform-implementation.js:42)
    at Object._emitValue (platform-implementation.js:42)
    at Object._handleValue (platform-implementation.js:42)
    at Object._handleAny (platform-implementation.js:42)
    at _$handleAny (platform-implementation.js:42)
    at m (platform-implementation.js:42)
    at _.dispatch (platform-implementation.js:42)
    at Object._emitValue (platform-implementation.js:42)
    at Object._handleValue (platform-implementation.js:42)
    at Object._handleAny (platform-implementation.js:42)
    at _$handleAny (platform-implementation.js:42)
    at m (platform-implementation.js:42)
    at _.dispatch (platform-implementation.js:42)
    at Object._emitValue (platform-implementation.js:42)
    at Object._handleValue (platform-implementation.js:42)
    at Object._handleAny (platform-implementation.js:42)
    at _$handleAny (platform-implementation.js:42) 

Original error stack:
Error: Failed to find element with selector: .J-KU-Jz
    at r (https://www.inboxsdk.com/build/platform-implementation.js:104:24019)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:92:30218)
    at new e (https://www.inboxsdk.com/build/platform-implementation.js:92:29058)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:93:14291)
    at t.value (https://www.inboxsdk.com/build/platform-implementation.js:110:23036)
    at chrome-extension://cjjlddlimmfkolnhphnohilankffhfbo/build/content-classes.js:985:18
    at i (https://www.inboxsdk.com/build/platform-implementation.js:105:5662)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:105:7168)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:105:6749)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:108:22007)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1606)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Ue._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Ue._handleSubAny (https://www.inboxsdk.com/build/platform-implementation.js:43:3573)
    at Oe._$handleSubAny (https://www.inboxsdk.com/build/platform-implementation.js:42:11261)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at Object._on (https://www.inboxsdk.com/build/platform-implementation.js:42:19352)
    at Object.onAny (https://www.inboxsdk.com/build/platform-implementation.js:42:16812)
    at Ue._addToCur (https://www.inboxsdk.com/build/platform-implementation.js:43:2939)
    at Ue._add (https://www.inboxsdk.com/build/platform-implementation.js:43:2433)
    at Ue._handleMain (https://www.inboxsdk.com/build/platform-implementation.js:43:5849)
    at Ue._$handleMain (https://www.inboxsdk.com/build/platform-implementation.js:42:11936)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Object._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Object._handleValue (https://www.inboxsdk.com/build/platform-implementation.js:42:24408)
    at Object._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:5036)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:4774)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Object._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Object._handleValue (https://www.inboxsdk.com/build/platform-implementation.js:42:24606)
    at Object._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:5036)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:4774)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Object._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Object._handleValue (https://www.inboxsdk.com/build/platform-implementation.js:42:24408)
    at Object._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:5036)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:4774) 

Error logged from:
    at o (https://www.inboxsdk.com/build/platform-implementation.js:80:26966)
    at u (https://www.inboxsdk.com/build/platform-implementation.js:107:7631)
    at Function.value (https://www.inboxsdk.com/build/platform-implementation.js:107:13053)
    at i (https://www.inboxsdk.com/build/platform-implementation.js:105:5686)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:105:7168)
    at e.value (https://www.inboxsdk.com/build/platform-implementation.js:105:6749)
    at eval (https://www.inboxsdk.com/build/platform-implementation.js:108:22007)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1606)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Ue._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Ue._handleSubAny (https://www.inboxsdk.com/build/platform-implementation.js:43:3573)
    at Oe._$handleSubAny (https://www.inboxsdk.com/build/platform-implementation.js:42:11261)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at Object._on (https://www.inboxsdk.com/build/platform-implementation.js:42:19352)
    at Object.onAny (https://www.inboxsdk.com/build/platform-implementation.js:42:16812)
    at Ue._addToCur (https://www.inboxsdk.com/build/platform-implementation.js:43:2939)
    at Ue._add (https://www.inboxsdk.com/build/platform-implementation.js:43:2433)
    at Ue._handleMain (https://www.inboxsdk.com/build/platform-implementation.js:43:5849)
    at Ue._$handleMain (https://www.inboxsdk.com/build/platform-implementation.js:42:11936)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Object._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Object._handleValue (https://www.inboxsdk.com/build/platform-implementation.js:42:24408)
    at Object._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:5036)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:4774)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Object._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Object._handleValue (https://www.inboxsdk.com/build/platform-implementation.js:42:24606)
    at Object._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:5036)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:4774)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574)
    at Object._emitValue (https://www.inboxsdk.com/build/platform-implementation.js:42:16232)
    at Object._handleValue (https://www.inboxsdk.com/build/platform-implementation.js:42:24408)
    at Object._handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:5036)
    at _$handleAny (https://www.inboxsdk.com/build/platform-implementation.js:42:4774)
    at m (https://www.inboxsdk.com/build/platform-implementation.js:42:1573)
    at _.dispatch (https://www.inboxsdk.com/build/platform-implementation.js:42:15574) 

Extension App Ids: [
  {
    "appId": "sdk_XXX"
  }
] 
Sent by App: false 
Session Id: 1525590328329-0.4598097815510951 
Extension Id: chrome-extension://cjjlddlimmfkolnhphnohilankffhfbo/ 
InboxSDK Loader Version: 0.7.24-1484787998857-c248fbb55be579d3 
InboxSDK Implementation Version: 0.7.24-1525481997680-ebf8ca812763a37d 
Is Using Sync API: false 
Is Using Material Gmail UI: false
```

**Comment by Macil** [comment]
Do you still get this error? Gmail has been changing the sidebar a lot because of add-ons lately and we've been continuously updating since then, so it may have been fixed in the meantime. If not, I'm really interested in hearing about this. I'm going to mark the issue closed since I think it's very likely the problem has been fixed in the meantime, but don't hesitate to respond.

**Comment by jesslombera** [comment]
@Macil Still getting this error when we hit registerThreadViewHandler . `Error details: {reason: "waiting for user account switcher", switcherHTML: Array(0)}`

It is only happening in classic
